name: market_pulse
version: "1.0"
profile: market_pulse

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  market_pulse:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  market_pulse:
    +quote_columns: false
